import type { GitHubRepo } from './types';

/**
 * Fallback repository data — scraped from the actual GitHub API on 2026-09-19.
 * Used when the live API is rate-limited or unavailable.
 */
export const fallbackRepos: GitHubRepo[] = [
    {
        id: 955428351,
        name: 'Cloud-Projects',
        full_name: 'ShahidKhan232/Cloud-Projects',
        html_url: 'https://github.com/ShahidKhan232/Cloud-Projects',
        description: 'AWS infrastructure and application projects demonstrating cloud automation, serverless architecture, and IaC best practices.',
        fork: false,
        language: 'HCL',
        stargazers_count: 3,
        forks_count: 5,
        watchers_count: 3,
        topics: [],
        updated_at: '2026-09-11T16:17:05Z',
        created_at: '2025-03-26T16:12:49Z',
        pushed_at: '2026-02-01T06:13:14Z',
        visibility: 'public',
        homepage: null,
        size: 35512,
        default_branch: 'main',
    },
    {
        id: 1261071410,
        name: 'Netflix-clone-k8s-end-to-end',
        full_name: 'ShahidKhan232/Netflix-clone-k8s-end-to-end',
        html_url: 'https://github.com/ShahidKhan232/Netflix-clone-k8s-end-to-end',
        description: 'Production-ready Netflix clone with React/TypeScript, Docker, Kubernetes, Jenkins CI/CD, Terraform IaC, and Prometheus/Grafana monitoring.',
        fork: false,
        language: 'TypeScript',
        stargazers_count: 0,
        forks_count: 0,
        watchers_count: 0,
        topics: [],
        updated_at: '2026-06-07T11:05:47Z',
        created_at: '2026-06-06T07:42:54Z',
        pushed_at: '2026-06-07T11:05:43Z',
        visibility: 'public',
        homepage: null,
        size: 42498,
        default_branch: 'main',
    },
    {
        id: 1114275505,
        name: 'Containerisation-and-Deployment-of-Wisecow-Application-on-Kubernetes-',
        full_name: 'ShahidKhan232/Containerisation-and-Deployment-of-Wisecow-Application-on-Kubernetes-',
        html_url: 'https://github.com/ShahidKhan232/Containerisation-and-Deployment-of-Wisecow-Application-on-Kubernetes-',
        description: 'Containerized application deployed on AWS EKS with Terraform-provisioned infrastructure and GitHub Actions CI/CD.',
        fork: false,
        language: 'HCL',
        stargazers_count: 0,
        forks_count: 0,
        watchers_count: 0,
        topics: [],
        updated_at: '2026-02-07T20:14:53Z',
        created_at: '2025-12-11T06:26:40Z',
        pushed_at: '2026-02-07T20:14:50Z',
        visibility: 'public',
        homepage: null,
        size: 7684,
        default_branch: 'main',
    },
    {
        id: 1151331610,
        name: 'Multi-Env-IaC',
        full_name: 'ShahidKhan232/Multi-Env-IaC',
        html_url: 'https://github.com/ShahidKhan232/Multi-Env-IaC',
        description: 'Reusable Terraform modules for dev, staging, and production environments with Ansible configuration management.',
        fork: false,
        language: 'HCL',
        stargazers_count: 0,
        forks_count: 0,
        watchers_count: 0,
        topics: [],
        updated_at: '2026-02-06T10:56:55Z',
        created_at: '2026-02-06T10:33:17Z',
        pushed_at: '2026-02-06T10:56:51Z',
        visibility: 'public',
        homepage: null,
        size: 515,
        default_branch: 'main',
    },
    {
        id: 1131114662,
        name: 'CI-CD-Ansible',
        full_name: 'ShahidKhan232/CI-CD-Ansible',
        html_url: 'https://github.com/ShahidKhan232/CI-CD-Ansible',
        description: 'Ansible playbooks for Nginx and MongoDB cluster configuration with Jenkins CI/CD automation.',
        fork: false,
        language: null,
        stargazers_count: 2,
        forks_count: 2,
        watchers_count: 2,
        topics: [],
        updated_at: '2026-01-16T09:50:38Z',
        created_at: '2026-01-09T13:54:19Z',
        pushed_at: '2026-01-10T05:11:50Z',
        visibility: 'public',
        homepage: null,
        size: 5181,
        default_branch: 'main',
    },
    {
        id: 972747804,
        name: 'AlertOps-Automated-Incident-Response-System',
        full_name: 'ShahidKhan232/AlertOps-Automated-Incident-Response-System',
        html_url: 'https://github.com/ShahidKhan232/AlertOps-Automated-Incident-Response-System',
        description: 'Complete monitoring solution using Prometheus, Grafana, Alertmanager, and Windows Exporter with Flask web app.',
        fork: false,
        language: 'Python',
        stargazers_count: 0,
        forks_count: 1,
        watchers_count: 0,
        topics: [],
        updated_at: '2026-02-07T20:19:51Z',
        created_at: '2025-04-25T15:38:53Z',
        pushed_at: '2026-02-07T20:19:48Z',
        visibility: 'public',
        homepage: null,
        size: 56237,
        default_branch: 'main',
    },
    {
        id: 1129831463,
        name: 'Docker-Project',
        full_name: 'ShahidKhan232/Docker-Project',
        html_url: 'https://github.com/ShahidKhan232/Docker-Project',
        description: 'Multi-container Docker project demonstrating containerization best practices.',
        fork: false,
        language: 'HTML',
        stargazers_count: 0,
        forks_count: 2,
        watchers_count: 0,
        topics: [],
        updated_at: '2026-01-15T17:48:51Z',
        created_at: '2026-01-07T16:38:54Z',
        pushed_at: '2026-01-15T17:48:45Z',
        visibility: 'public',
        homepage: null,
        size: 23841,
        default_branch: 'main',
    },
    {
        id: 994855718,
        name: 'Full-stack-cicd-pipeline',
        full_name: 'ShahidKhan232/Full-stack-cicd-pipeline',
        html_url: 'https://github.com/ShahidKhan232/Full-stack-cicd-pipeline',
        description: 'End-to-end CI/CD pipeline for a full-stack application using Docker.',
        fork: false,
        language: 'Dockerfile',
        stargazers_count: 0,
        forks_count: 0,
        watchers_count: 0,
        topics: [],
        updated_at: '2026-01-11T05:29:36Z',
        created_at: '2025-06-02T15:28:10Z',
        pushed_at: '2025-06-03T15:32:23Z',
        visibility: 'public',
        homepage: null,
        size: 284,
        default_branch: 'main',
    },
    {
        id: 1128230560,
        name: 'AWS-codepipeline',
        full_name: 'ShahidKhan232/AWS-codepipeline',
        html_url: 'https://github.com/ShahidKhan232/AWS-codepipeline',
        description: 'AWS CodePipeline implementation for automated deployment workflows.',
        fork: false,
        language: 'JavaScript',
        stargazers_count: 0,
        forks_count: 0,
        watchers_count: 0,
        topics: [],
        updated_at: '2026-01-05T16:35:00Z',
        created_at: '2026-01-05T10:30:11Z',
        pushed_at: '2026-01-05T16:34:57Z',
        visibility: 'public',
        homepage: null,
        size: 7026,
        default_branch: 'main',
    },
    {
        id: 1019565057,
        name: 'Devops-Project',
        full_name: 'ShahidKhan232/Devops-Project',
        html_url: 'https://github.com/ShahidKhan232/Devops-Project',
        description: 'DevOps infrastructure project with Terraform IaC for AWS resource provisioning.',
        fork: false,
        language: 'HCL',
        stargazers_count: 0,
        forks_count: 0,
        watchers_count: 0,
        topics: [],
        updated_at: '2026-01-11T05:29:37Z',
        created_at: '2025-07-14T14:20:10Z',
        pushed_at: '2025-07-28T12:32:47Z',
        visibility: 'public',
        homepage: null,
        size: 2680,
        default_branch: 'main',
    },
    {
        id: 1154487665,
        name: 'Kubernetes-Troubleshooting',
        full_name: 'ShahidKhan232/Kubernetes-Troubleshooting',
        html_url: 'https://github.com/ShahidKhan232/Kubernetes-Troubleshooting',
        description: 'Kubernetes troubleshooting guides and common issue resolution strategies.',
        fork: false,
        language: null,
        stargazers_count: 0,
        forks_count: 0,
        watchers_count: 0,
        topics: [],
        updated_at: '2026-02-11T14:02:59Z',
        created_at: '2026-02-10T12:53:41Z',
        pushed_at: '2026-02-11T14:02:59Z',
        visibility: 'public',
        homepage: null,
        size: 95,
        default_branch: 'main',
    },
    {
        id: 1112978960,
        name: 'Kodekloud_Engineer_solution',
        full_name: 'ShahidKhan232/Kodekloud_Engineer_solution',
        html_url: 'https://github.com/ShahidKhan232/Kodekloud_Engineer_solution',
        description: 'Solutions to KodeKloud Engineer tasks covering Linux, Docker, Kubernetes, and Ansible.',
        fork: false,
        language: null,
        stargazers_count: 0,
        forks_count: 0,
        watchers_count: 0,
        topics: [],
        updated_at: '2026-02-10T17:23:59Z',
        created_at: '2025-12-09T11:04:57Z',
        pushed_at: '2026-02-10T17:23:56Z',
        visibility: 'public',
        homepage: null,
        size: 90,
        default_branch: 'main',
    },
    {
        id: 1114939450,
        name: 'Scripts',
        full_name: 'ShahidKhan232/Scripts',
        html_url: 'https://github.com/ShahidKhan232/Scripts',
        description: 'Python automation scripts for system administration and DevOps tasks.',
        fork: false,
        language: 'Python',
        stargazers_count: 0,
        forks_count: 0,
        watchers_count: 0,
        topics: [],
        updated_at: '2025-12-12T05:57:53Z',
        created_at: '2025-12-12T05:32:03Z',
        pushed_at: '2025-12-12T05:57:49Z',
        visibility: 'public',
        homepage: null,
        size: 324,
        default_branch: 'main',
    },
    {
        id: 1077598612,
        name: 'KisanSaathi',
        full_name: 'ShahidKhan232/KisanSaathi',
        html_url: 'https://github.com/ShahidKhan232/KisanSaathi',
        description: 'Agricultural platform built with TypeScript/Next.js.',
        fork: false,
        language: 'TypeScript',
        stargazers_count: 0,
        forks_count: 0,
        watchers_count: 0,
        topics: [],
        updated_at: '2026-02-09T17:36:03Z',
        created_at: '2025-10-16T13:24:00Z',
        pushed_at: '2026-03-11T16:08:45Z',
        visibility: 'public',
        homepage: null,
        size: 2719,
        default_branch: 'main',
    },
    {
        id: 1194279615,
        name: 'Smart-File-Upload-System',
        full_name: 'ShahidKhan232/Smart-File-Upload-System',
        html_url: 'https://github.com/ShahidKhan232/Smart-File-Upload-System',
        description: 'Intelligent file upload system with drag-and-drop and cloud storage integration.',
        fork: false,
        language: 'CSS',
        stargazers_count: 0,
        forks_count: 0,
        watchers_count: 0,
        topics: [],
        updated_at: '2026-03-28T07:43:54Z',
        created_at: '2026-03-28T06:11:42Z',
        pushed_at: '2026-03-28T07:43:50Z',
        visibility: 'public',
        homepage: 'https://smart-file-upload-system.vercel.app',
        size: 12217,
        default_branch: 'main',
    },
    {
        id: 1175792001,
        name: 'FreshMart',
        full_name: 'ShahidKhan232/FreshMart',
        html_url: 'https://github.com/ShahidKhan232/FreshMart',
        description: 'E-commerce grocery platform with responsive design.',
        fork: false,
        language: 'HTML',
        stargazers_count: 0,
        forks_count: 0,
        watchers_count: 0,
        topics: [],
        updated_at: '2026-03-08T07:07:46Z',
        created_at: '2026-03-08T07:06:22Z',
        pushed_at: '2026-03-08T07:07:06Z',
        visibility: 'public',
        homepage: 'https://fresh-mart-fawn.vercel.app',
        size: 8321,
        default_branch: 'main',
    },
    {
        id: 1174579895,
        name: 'Phoenix-College',
        full_name: 'ShahidKhan232/Phoenix-College',
        html_url: 'https://github.com/ShahidKhan232/Phoenix-College',
        description: 'College website with responsive design and department pages.',
        fork: false,
        language: 'HTML',
        stargazers_count: 0,
        forks_count: 0,
        watchers_count: 0,
        topics: [],
        updated_at: '2026-03-06T16:22:27Z',
        created_at: '2026-03-06T15:52:44Z',
        pushed_at: '2026-03-06T16:22:23Z',
        visibility: 'public',
        homepage: 'https://phoenix-college.vercel.app',
        size: 40,
        default_branch: 'main',
    },
    {
        id: 1157686100,
        name: 'Credit_Approval_System',
        full_name: 'ShahidKhan232/Credit_Approval_System',
        html_url: 'https://github.com/ShahidKhan232/Credit_Approval_System',
        description: 'Machine learning-based credit approval system using Python.',
        fork: false,
        language: 'Python',
        stargazers_count: 0,
        forks_count: 0,
        watchers_count: 0,
        topics: [],
        updated_at: '2026-02-14T06:14:27Z',
        created_at: '2026-02-14T06:11:43Z',
        pushed_at: '2026-02-14T06:14:23Z',
        visibility: 'public',
        homepage: null,
        size: 418,
        default_branch: 'main',
    },
    {
        id: 871544492,
        name: 'FingerPrint-Matcher',
        full_name: 'ShahidKhan232/FingerPrint-Matcher',
        html_url: 'https://github.com/ShahidKhan232/FingerPrint-Matcher',
        description: 'Python-based fingerprint matching using image processing algorithms.',
        fork: false,
        language: 'Python',
        stargazers_count: 0,
        forks_count: 1,
        watchers_count: 0,
        topics: [],
        updated_at: '2026-01-14T12:38:06Z',
        created_at: '2024-10-12T08:59:38Z',
        pushed_at: '2026-01-14T12:38:02Z',
        visibility: 'public',
        homepage: null,
        size: 9,
        default_branch: 'main',
    },
    {
        id: 1062309610,
        name: 'Real-Time-Twitter-Sentiment-Analysis',
        full_name: 'ShahidKhan232/Real-Time-Twitter-Sentiment-Analysis',
        html_url: 'https://github.com/ShahidKhan232/Real-Time-Twitter-Sentiment-Analysis',
        description: 'Real-time Twitter sentiment analysis using Kafka, Spark Streaming, MongoDB, and Django.',
        fork: true,
        language: null,
        stargazers_count: 0,
        forks_count: 0,
        watchers_count: 0,
        topics: [],
        updated_at: '2025-09-23T05:07:02Z',
        created_at: '2025-09-23T05:07:02Z',
        pushed_at: '2024-05-20T20:01:31Z',
        visibility: 'public',
        homepage: '',
        size: 5337,
        default_branch: 'main',
    },
    {
        id: 871324316,
        name: 'Atttendence-Notifier',
        full_name: 'ShahidKhan232/Atttendence-Notifier',
        html_url: 'https://github.com/ShahidKhan232/Atttendence-Notifier',
        description: 'Python-based attendance notification system for automated tracking.',
        fork: false,
        language: 'Python',
        stargazers_count: 0,
        forks_count: 0,
        watchers_count: 0,
        topics: [],
        updated_at: '2024-10-11T18:18:49Z',
        created_at: '2024-10-11T18:08:04Z',
        pushed_at: '2024-10-11T18:18:46Z',
        visibility: 'public',
        homepage: null,
        size: 6,
        default_branch: 'main',
    },
    {
        id: 870814654,
        name: 'Tours-and-Travels-website',
        full_name: 'ShahidKhan232/Tours-and-Travels-website',
        html_url: 'https://github.com/ShahidKhan232/Tours-and-Travels-website',
        description: 'Responsive tours and travel website with booking interface.',
        fork: false,
        language: 'CSS',
        stargazers_count: 0,
        forks_count: 0,
        watchers_count: 0,
        topics: [],
        updated_at: '2024-10-11T18:12:23Z',
        created_at: '2024-10-10T18:04:24Z',
        pushed_at: '2024-10-11T18:12:19Z',
        visibility: 'public',
        homepage: null,
        size: 3426,
        default_branch: 'main',
    },
    {
        id: 943991966,
        name: 'SheildMe',
        full_name: 'ShahidKhan232/SheildMe',
        html_url: 'https://github.com/ShahidKhan232/SheildMe',
        description: 'Mobile safety application built with Dart/Flutter.',
        fork: false,
        language: 'Dart',
        stargazers_count: 0,
        forks_count: 0,
        watchers_count: 0,
        topics: [],
        updated_at: '2025-03-06T15:55:04Z',
        created_at: '2025-03-06T15:52:19Z',
        pushed_at: '2025-03-06T15:54:38Z',
        visibility: 'public',
        homepage: null,
        size: 5748,
        default_branch: 'main',
    },
    {
        id: 943788373,
        name: 'codebits_3.0',
        full_name: 'ShahidKhan232/codebits_3.0',
        html_url: 'https://github.com/ShahidKhan232/codebits_3.0',
        description: 'Hackathon project built with Dart/Flutter during CodeBits 3.0.',
        fork: true,
        language: 'Dart',
        stargazers_count: 0,
        forks_count: 0,
        watchers_count: 0,
        topics: [],
        updated_at: '2025-06-24T10:46:53Z',
        created_at: '2025-03-06T09:12:30Z',
        pushed_at: '2025-06-24T10:46:49Z',
        visibility: 'public',
        homepage: null,
        size: 288,
        default_branch: 'main',
    },
    {
        id: 1004933402,
        name: 'devops-cheatsheet',
        full_name: 'ShahidKhan232/devops-cheatsheet',
        html_url: 'https://github.com/ShahidKhan232/devops-cheatsheet',
        description: 'Comprehensive DevOps cheatsheet covering CI/CD, containerization, monitoring, security, and networking.',
        fork: true,
        language: 'TypeScript',
        stargazers_count: 0,
        forks_count: 0,
        watchers_count: 0,
        topics: [],
        updated_at: '2026-01-11T05:29:39Z',
        created_at: '2025-06-19T12:01:09Z',
        pushed_at: '2026-01-06T14:41:09Z',
        visibility: 'public',
        homepage: 'https://cheatsheet.prodevopsguytech.com',
        size: 600,
        default_branch: 'master',
    },
    {
        id: 1369817604,
        name: 'ultimate-linux-guide',
        full_name: 'ShahidKhan232/ultimate-linux-guide',
        html_url: 'https://github.com/ShahidKhan232/ultimate-linux-guide',
        description: 'Ultimate guide to learn Linux from scratch.',
        fork: true,
        language: null,
        stargazers_count: 0,
        forks_count: 0,
        watchers_count: 0,
        topics: [],
        updated_at: '2026-09-14T11:33:37Z',
        created_at: '2026-09-14T11:33:37Z',
        pushed_at: '2025-09-22T10:39:28Z',
        visibility: 'public',
        homepage: null,
        size: 17,
        default_branch: 'main',
    },
];
